### PR TITLE
feat: logging into a file

### LINKED ISSUE #117: testground: pipe out all big logs
We need to think about piping out all logs from pods better way that is done currently in testground

Place where to start digging into it: 
- https://github.com/testground/testground/blob/ac27f8134651cfb995e54dfda81ae252b3049ff5/pkg/runner/cluster_k8s.go#L392

What we want to is essentially refactor this `getPodLogs` into a stream event that dumps logs immediately into some files instead of waiting for the end of pods execution if I understood the code-base correctly 

Ref: 

- https://github.com/testground/testground/issues/1450
- https://github.com/testground/testground/issues/1039

### PR DESCRIPTION
**Pull request by Bidon15**
## Overview

Fixes #117 

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Comment by jrmanes** [comment]
hello @Bidon15 

let me share my thoughts, so as we are having the env vars:
```
ENV GOLOG_LOG_FMT="json"
ENV GOLOG_FILE /var/log/node.log
```
what do you think if in the file `testkit/appkit/app.go`, before apply the [flag](https://github.com/celestiaorg/test-infra/blob/c1c968ec0bb2b6d1b5b73eaed46040f0924f43c0/testkit/appkit/app.go#L209-L211), we check the env vars and depending on which value, we send the logs to a `file` or to `stdout`.

I mean, in case we have to send the logs to a files, we should take care of these files and it would be even better if we can set a `logrotate` policy in order to prevent that these files will grow without control...

Best! 🚀

**Comment by Bidon15** [comment]
> hello @Bidon15
> 
> let me share my thoughts, so as we are having the env vars:
> 
> ```
> ENV GOLOG_LOG_FMT="json"
> ENV GOLOG_FILE /var/log/node.log
> ```
> 
> what do you think if in the file `testkit/appkit/app.go`, before apply the [flag](https://github.com/celestiaorg/test-infra/blob/c1c968ec0bb2b6d1b5b73eaed46040f0924f43c0/testkit/appkit/app.go#L209-L211), we check the env vars and depending on which value, we send the logs to a `file` or to `stdout`.
> 
> I mean, in case we have to send the logs to a files, we should take care of these files and it would be even better if we can set a `logrotate` policy in order to prevent that these files will grow without control...
> 
> Best! 🚀

Hey @jrmanes. These env vars are only applicable for `celestia-node` for now as I'm still not aware of how to get this to app side

For app I suppose we need this: https://github.com/celestiaorg/celestia-app/pull/1449/files#diff-2e0a28b322712419d84cdc4b09cea11fd4c9f680b00d7408578544b57d716a13R45-R50

**Comment by jrmanes** [comment]
> > hello @Bidon15
> > let me share my thoughts, so as we are having the env vars:
> > ```
> > ENV GOLOG_LOG_FMT="json"
> > ENV GOLOG_FILE /var/log/node.log
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > what do you think if in the file `testkit/appkit/app.go`, before apply the [flag](https://github.com/celestiaorg/test-infra/blob/c1c968ec0bb2b6d1b5b73eaed46040f0924f43c0/testkit/appkit/app.go#L209-L211), we check the env vars and depending on which value, we send the logs to a `file` or to `stdout`.
> > I mean, in case we have to send the logs to a files, we should take care of these files and it would be even better if we can set a `logrotate` policy in order to prevent that these files will grow without control...
> > Best! 🚀
> 
> Hey @jrmanes. These env vars are only applicable for `celestia-node` for now as I'm still not aware of how to get this to app side
> 
> For app I suppose we need this: https://github.com/celestiaorg/celestia-app/pull/1449/files#diff-2e0a28b322712419d84cdc4b09cea11fd4c9f680b00d7408578544b57d716a13R45-R50

Hello @Bidon15 

thanks for the context, it's much clear now :)
you could check this topic in the future and try to use the env vars in the app side as well

cheers! 😊

**Review by jrmanes — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
